feat: Switch to support Databricks Spark runtime
Databricks has their own fork of Spark that made `genCode` method final, any attempt
to override it throws an error. Instead, they made `genCodeInternal`method available
for overrides.

Original error:

  java.lang.VerifyError: class org.apache.spark.sql.FramelessInternals$DisambiguateRight overrides final method genCode.
  (Lorg/apache/spark/sql/catalyst/expressions/codegen/CodegenContext;)Lorg/apache/spark/sql/catalyst/expressions/codegen/ExprCode;

Note: I'm skipping `override` keyword, since `Expression` is an abstract class and it's not required,
but it also gives an opportunity to compile `frameless` without access to Databricks Spark jars.